---
- hosts: all
  remote_user: admuser
  tasks:
    - name: Get Service Status
      ansible.builtin.systemd:
        name: "xagt.service"
      register: service_status

    - debug:
        var: service_status.status.ActiveState
