---
- hosts: all
  remote_user: admuser
  steps:
    - tasks:
        - name: Get Service Status
          ansible.builtin.systemd:
            name: xagt.service
            register: xagt_service_status
        - debug:
            var: pg_service_status.status.ActiveState
