---
- name: checking service status
  hosts: UaeMaSposDeFoP1
  tasks:
    - name: checking service status
      command: systemctl status "{{ item }}"
      with_items:
        - xagt.service
        - sshd
      register: stdout_lines 
      ignore_errors: yes
    - name: showing report
      debug:
        var: stdout_lines

